{% set version = "1.0.3" %}

package:
  name: doct
  version: {{ version }}

source:
  url: http://github.com/NSLS-II/doct/archive/v{{ version }}.tar.gz
  fn: doct-{{ version }}.tar.gz
  sha256: 4546ad1403492fea49eab74f1bb84149ab3eb7c705d13f157b20f0489f3da97e

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python

  run:
    - humanize
    - prettytable
    - python
    - six

test:
  requires:
    - nose
    - six
  commands:
    - nosetests ../work/doct-{{ version }} -sv
  imports:
    - doct

about:
  home: https://github.com/NSLS-II/document
  license: BSD 3-Clause
  summary: A read-only dottable dictionary

extra:
  recipe-maintainers:
    - ericdill
