{% set version = "1.1.0" %}

package:
  name: doct
  version: {{ version }}

source:
  url: http://github.com/NSLS-II/doct/archive/v{{ version }}.tar.gz
  fn: doct-{{ version }}.tar.gz
  sha256: 966930179cce0788d922d877c65385bd851df5dc2f0a1009579607e3eed6bd5c

build:
  number: 1
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - humanize
    - prettytable
    - python {{ python_min }}
    - six
    - setuptools
  run:
    - humanize
    - prettytable
    - python >={{ python_min }}
    - six 

test:
  requires:
    - python {{ python_min }}
  imports:
    - doct

about:
  home: https://github.com/NSLS-II/document
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A read-only dottable dictionary

extra:
  recipe-maintainers:
    - CJ-Wright
    - tacaswell
    - licode
    - danielballan
