travis:
  secure:
    BINSTAR_TOKEN: KXMPGU2MtuNynMZl/uZ4fKW6fewtgNd7SplBqE9uoslaP0kVUT97NpXY4sxsvWMJGyDjjbh5zkBrvk7D1gLs5cY9DAy9RAx2uPKgC2JwcpChWrQHd44nG0FphgCpjLokgS09BudbOm/qmFZT9mXbFRfiq98HJ3k2+1xuwo+ooAQUJxMo6PYvyXGD5QPc+MplWAETMwBUleatseP/CKgsHRGtDSowl6PWzSqnY7QsQOXNpZesxXWi2RGnun6bjmDjEIT46SAMPu6lKPEySP1zVIgb9vidUl3wMA4kURxAss4TAsY9X3dYNpM/vibgjUGHPJf59DoIOkOWZr/uyNvlNkVhqD2bSepCaOHDUkjLeDs2nMrOIipW/TKsUJ+TuMszSfjpk/lboDbwifYP7Umn+XNG6T0CixtmmyIMU1D200rLI4ZvfXNdYA0P7f25pO5PrBHw7eUzgEVsy46Ja7dRo45FL8iNSf+zQlpw9zwzL8240ozMj14X5lyVAyNrX1BNftIo6FueR8/K/PDSdgMdb9DNkkijhOnfKOpWewE2NQrd6jwQD21R9ep0GxDEI/Xz7WnBlUr8ODwDyzOglVuXhXD6gTUnv7Fa6Qh/NBDDghRrNbIqnZUcUwwj7hvxdCNSIg2KUtMNqJ1pnmTmtM5FNILYfbmOdaFgm94E/pXYOpY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
