travis:
  secure:
    BINSTAR_TOKEN: diQxYHEANLvFPBuipEAOUFQKy1hHbNJ2L+LuAG3hESiYAtxSBOPUxuuGK+DzDLffjHxzJAYiIM2SPt3Sr2yJeImMMiFDwjXSSQzw8Mf/9fhnBNuDx64awnScecBAT0tDuk2Vn30SFncvmnAtYo9kagjVuOx+ehyzhG6LyarGHc/vUTCJEdfhiMBpkYJuRxnGodvsOpbrB5Z54fR8HBDLt87UyzpShojL6PhLZLc/F9pIQNK+NSBbCgWCoMjXHXFibbUrRADHQfyKT8rPL3l2QHQ1xs8DYfqTENs+1VfP9t6BNpCrYn8J1HtsrmvhKoDmyE5kUVoNpbN5k+euTH8tngAXZhyZrdWCT+RGgjrMARcS+I258AQGqyVmiLLQmNGkdunoJtAOL8kl9kP9dAkYWPbqdXrHpY593Adkfe2j/Ltwlr2CeTRk15nqAgzAb4kCKFc43WXhYeFURC6pGm/bKrOPV+Beq/deSODtbfZ1Up/zGb53pbfQV9Ops3iKUlptfH5OK3fTqR2rI7mX+ZjKaadpdAs9Ej1lJP0DF+gDkik0afpx+OqjkDgLV0SViuvvuIg2qOwvhTlyQlPf55vI/TVQFrfXjbAJBA5T8iVa/8e7XFWULN8pFQWkZ1m7YpzSGeVhPEVAiTzE0VsMdJpRDqc4Zjxdm92OxA549ps8WrQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
