travis:
  secure:
    BINSTAR_TOKEN: q3DlNUKUN8guduGGXDvf4MLHu9DVeSshpLMb1my1ncKKRWk460YLYkmch6Gkmib5aRuG1PCjCb3ovQK/vbbJjORX5WOpOeujWtmZ6m/yVBpogm4o8YQ1ky35vkCmLfMFHoMM3xPLjjOqtoYFY3RyT7TxcZJToZVFVSr2vIqP3PujqLVYg5531pdY3MvqD5EptgVCBwUihTVDwbb7+8nwOE9GK2k4jTL3lP7mZPGxYlQFKvwhfubrW6knXtiOfAcw/3n7FRvdltSOtMVObhgFRdgaJ4vLrJKBH8CnaTN+uyqlelYzJuGoa806croX7NwkQ1XSo2NAEhTHK/7LFHqGMZ6i+dgD7tSmxhHhVpQE/ixM2K55xYe+05qbxVlySw7xEdpFDEQglSN0iUCDTN4crQWqx7fK05NBJOENDK4bOcuW/05HX+mOq06Jms+5+4QCiThRlNIHhyV/VWRcXGlIP5zVuWP1vxdnuv/Uvb82q5T2CMNrVLpmoYZZrdunHYqMfgbe7O7jG/nwyqgpRrl7XMGJ351aMES7nvJVnkX0ravVySoyEF0C8IylDdn67ZG4/VbrzVQm3vVYwX7weqNKZxpr3ob0sWC6vm5gsG6L4BEd2GzQljIsR5Uvrg0XOhPHtwzBkx2RZXAAhVMjtPUzbbn3bP09keuo59i09DxT9XY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
