travis:
  secure:
    BINSTAR_TOKEN: Cb7GNOuDAJRrztHHyiKWsWUEeel/uqMTA/MfWGSXUWW7MOT/lQIO4z8Way74uRuzAqs5tK61ImQSAVoPb7gf9Fhq8HvZuNDW/hOBIb0euvMpJOQFniZkRxc0BhIvnQHqloxMzVFozQhDPS9eaVipIa91xnjhHsz4Rja320A4ge/0E012wlBPkcIqEWh5bQyQ+Tb+Ahv+MITGveInYv3POFUrAyK4ZFXrq/qnURQqBFz3uUjBd70h5iUaMg5F4ngLH5VAhPm/gZyYypnGoyQVNOMfW5vWVC5uc8pPY3+2LK6mBXDHLglQqTndK749ZZC1FRyl8FEwc7OzhP/9QtzF6VMZdz22axDQ/e5dZ4540vX96lmwfsY+KgPYmh/1o7k9XxUsrtiK2WdNR2MsP+SnQaPyEjVlRKRJPrqHyq4ocKxaLxWCtX+MFWsIIXNncWbZOp7frC0HDIYjIC1EruUspAr3bJgGFNPDuAcEGMw2BfQvA5+69bE7L9yn4b9rOjT1Tu+WK2Wt2yQ55vfVUMlDv/x8TsTy08at+avFNmw1ufcEbyTZMNBFnLUkrGkD48Ge9pj5JFq6nUO+Nt2yFoUM39tFq/hZi13AXvtjLPfCOJk2fK+oof3wuuvdZUytZsy3GIVDWi7I4aMZe4sTIFZHXpcd+6W9rDPvCq00KW8DuBU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
